In [ ]:
# ドライブ読み込み
from google.colab import drive
drive.mount('/content/drive')
%cd "/content/drive/My Drive/Colab Notebooks"

Mounted at /content/drive
/content/drive/My Drive/Colab Notebooks


In [ ]:
!pip install japanize_matplotlib

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.1/4.1 MB 20.3 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
  Created wheel for japanize_matplotlib: filename=japanize_matplotlib-1.1.3-py3-none-any.whl size=4120257 sha256=0a93999b02db66c9e70b63418dff08c9703530e06faa785762011ad72298a853
  Stored in directory: /root/.cache/pip/wheels/61/7a/6b/df1f79be9c59862525070e157e62b08eab8ece27c1b68fbb94
Successfully built japanize_matplotlib


In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import japanize_matplotlib
import seaborn as sns
import sympy
import math
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.linear_model import LinearRegression, Ridge, Lasso
from PIL import Image
import sys

img2array(file_pass)

In [ ]:
# ファイル名 or ファイルパスを指定した画像を NumPy配列 にして返す関数を定義
def img2array(file_path):
    img_c1 = Image.open(file_path).convert("L")
#    plt.imshow(img_c1, cmap="gray")
#    plt.show()

    img_c2 = img_c1.resize((8,8),Image.LANCZOS)
#    plt.imshow(img_c2, cmap="gray")
#    plt.show()

    img_arr1 = np.asarray(img_c2, dtype=float)
    print(img_arr1)

    img_arr2 = 16 - np.floor(17 * img_arr1/256)
    print(img_arr2)
#    plt.imshow(img_arr2, cmap="gray")
#    plt.show()

    img_arr3 = img_arr2.reshape(1,-1)
    print(img_arr3.shape)
    return img_arr3

imgs2csv(file_list, csv_name)

In [ ]:
def imgs2csv(file_list, csv_name):
    csv_array = np.empty((0,64),float)
    for img_path in file_list:
        #print(img2array(img_path))
        csv_array = np.append(csv_array, img2array(img_path), axis=0)

    h_str = ",".join(["x"+str(i) for i in range(1,65)])
    np.savetxt(csv_name, csv_array, delimiter=",", comments="", header=h_str)
    return csv_array

# pngとjpgの取り出し

In [ ]:
import glob
file_list = glob.glob('./png_2023re/*.png') + glob.glob('./png_2023re/*.jpg')
print(file_list)

['./png_2023re/953015_shikaku_.png', './png_2023re/953015_sankaku_.png', './png_2023re/953015_batsu_1.png', './png_2023re/953015_batsu_.png', './png_2023re/953007_batsu_.png', './png_2023re/953009_shikaku_2.png', './png_2023re/953007_sankaku_.png', './png_2023re/953007_maru_.png', './png_2023re/953015_sankaku_1.png', './png_2023re/953009_shikaku_.png', './png_2023re/953009_sankaku_2.png', './png_2023re/953015_maru_.png', './png_2023re/953009_maru_2.png', './png_2023re/953009_sankaku_.png', './png_2023re/953007_shikaku_.png', './png_2023re/953015_maru_1.png', './png_2023re/953009_maru_.png', './png_2023re/953077_batsu_.png', './png_2023re/953015_shikaku_1.png', './png_2023re/953057_sankaku_.png', './png_2023re/953086_shikaku_2.png', './png_2023re/953086_batsu_2.png', './png_2023re/953030_shikaku_.png', './png_2023re/953086_shikaku_1.png', './png_2023re/953057_shikaku_.png', './png_2023re/953048_sankaku_2.png', './png_2023re/953030_maru_2.png', './png_2023re/953017_shikaku_.png', './png_

In [ ]:
import glob
import os

# "png_2023re"フォルダ内の png ファイルだけをリスト化
dir_path = './png_2023re/*.png'
png_list = glob.glob(dir_path)
#print(png_list)

# 拡張子とファイル名を抜き出す処理
for x in png_list:
    print("ファイルパスは")
    print(x)
    print("ファイル名は")
    print(os.path.basename(x))
    name, ext = os.path.splitext(x)
    print("ファイル名(拡張子除く)は")
    print(name)
    print("拡張子(だけ)は")
    print(ext)
    print()

#(2)

“png_2023re” フォルダ内の jpg もしくは png 拡張子を持つ画像（全部で 84
枚）のファイル名をリストで取得し、(1)を利用して 84 枚すべてを一気に CSV
データにしなさい。
なお、出力する CSV ファイルは “mini_enshu14_1.csv” と名付けること。


In [ ]:
imgs2csv(file_list, "mini_enshu14_1.csv")

[[255. 255. 255. 255. 255. 255. 255. 255.]
 [254. 255. 236. 223. 255. 255. 254. 255.]
 [255. 249. 214. 224. 214. 248. 255. 255.]
 [253. 220. 242. 255. 240. 215. 234. 254.]
 [231. 209. 255. 254. 255. 237. 217. 255.]
 [253. 234. 212. 249. 248. 213. 254. 254.]
 [255. 255. 245. 212. 208. 248. 255. 255.]
 [255. 254. 255. 250. 243. 255. 254. 255.]]
[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 2. 0. 0. 0. 0.]
 [0. 0. 2. 2. 2. 0. 0. 0.]
 [0. 2. 0. 0. 1. 2. 1. 0.]
 [1. 3. 0. 0. 0. 1. 2. 0.]
 [0. 1. 2. 0. 0. 2. 0. 0.]
 [0. 0. 0. 2. 3. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]
(1, 64)
[[255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 248. 215. 255. 255. 255.]
 [255. 254. 249. 207. 203. 250. 255. 255.]
 [254. 255. 215. 245. 232. 237. 255. 254.]
 [255. 221. 230. 255. 242. 224. 255. 254.]
 [254. 218. 217. 223. 240. 213. 252. 255.]
 [255. 255. 251. 236. 223. 207. 250. 255.]
 [255. 254. 255. 255. 255. 255. 255. 255.]]
[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 2. 0. 0. 0.]
 [0. 0. 0. 3. 3. 0. 0. 0.]
 [0.

array([[ 5.,  4.,  7., ...,  9.,  7.,  6.],
       [11., 10., 10., ...,  9.,  8.,  6.],
       [ 1.,  5.,  7., ...,  7.,  9., 10.],
       ...,
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.]])

# (3)

“png_2023re” というフォルダ内の jpg もしくは png 拡張子を持つ画像を、一括
で CSV データ化する関数を定義しなさい。
なお、関数名は folder2csv() と名付けること。

In [ ]:
# # 画像の数値化
# def folder2csv(folder_name, csv_name, extension_name):
#     # 探したい画像の拡張子の取り出しと一括化
#     file_list = []
#     for e in extension_name:
#         file_list.extend(glob.glob(folder_name + '*' + e))

#     # 数値化
#     csv_array = np.empty((0, 64), float)
#     for img_path in file_list:
#         img_c1 = Image.open(img_path).convert("L")
#         img_c2 = img_c1.resize((8, 8), Image.LANCZOS)
#         img_arr1 = np.asarray(img_c2, dtype=float)
#         img_arr2 = 16 - np.floor(17 * img_arr1/256)
#         img_arr3 = img_arr2.reshape(1, -1)
#         csv_array = np.append(img_arr3, csv_array, axis=0)

#     h_str = ",".join(["x"+str(i) for i in range(1, 65)])
#     # セーブする
#     np.savetxt(csv_name, csv_array, delimiter=",", comments="", header=h_str)
#     # 表示
#     return csv_array


In [ ]:
# (3)の模範解答
def folder2csv(dir_name, csv_name, ex_list):
    file_list = glob.glob(dir_path + '*.*')
    img_list = []

    for file_name in file_list:
        name, ext = os.path.splitext(file_name)
        if ext in ex_list:
          img_list.append(file_name)

    img_array = imgs2csv(img_list, csv_name)
    return img_array


# (4)

folder2csv()関数を、”png_2023re”フォルダに作用させ、
CSV ファイルを生成しなさい。
なお、出力する CSV ファイルは “mini_enshu14_2.csv” と名付けること。


In [ ]:
folder2csv("./png_2023re/", "mini_enshu14_2.csv", ['.png','.jpg'])

array([[ 5.,  4.,  7., ...,  9.,  7.,  6.],
       [11., 10., 10., ...,  9.,  8.,  6.],
       [ 1.,  5.,  7., ...,  7.,  9., 10.],
       ...,
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.]])